### ISSUE TITLE
bruh momentos

### ISSUE THREAD

**Issue by ghost** [RedstoneParadox/NiceToHave#8] opened 2019-08-10 17:24 UTC
**Nice to Have version:**
1.1.0
**Fabric Loader Version:**
latest
**Fabric API Version:**
latest
**Mappings version:**
latest
**Fabric Language Kotlin Version:**
latest
**Name and version of any other mods present:**
too much
**What actually happened:**
like, i like the dynamite and wanted it on mp but couldn't, mod doesn't work mp
and it crashes with engination SO THAT MAKES ME ANGRY
**Steps to reproduce:**
1. fabric server
2. nice to have
3. open but actually can't.
AND
1. fabric server
2. nice to have
3. engination
4. open but actually can't

**Comment by RedstoneParadox** [comment] 2019-08-10 17:29
Please don't report two issues in the same issue report and check to see if you actually have the latest version of stuff because you actually don't have the latest Nice to Have version (I released another one 20 minutes ago here and on Curse) and next time check if an issue is a duplicate because the second issue is a duplicate of #7.

Also, if there are too many mods to list, just attach a log file or something.

**Closed as completed by RedstoneParadox** 2019-08-10 17:29 UTC
Labels: duplicate
